services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WS_DB_PORT:-5432}:5432
    environment:
        POSTGRES_USER: ${WS_DB_USER}
        POSTGRES_PASSWORD: ${WS_DB_PWD}
        POSTGRES_DB: ${WS_DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "bar"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
